---
variables:
  CLOUD_IMAGE_VERSION: dev
  CLOUD_IMAGE_NAME: debian-${CLOUD_IMAGE_RELEASE}-${CLOUD_IMAGE_VERSION}-${CLOUD_VENDOR}-${CLOUD_ARCH}

.build: &build
  stage: build
  image: debian:stretch-backports
  script:
    - apt-get update
    - >
      apt-get install --no-install-recommends -y -t stretch-backports
      ca-certificates debsums fai-server fai-setup-storage make python3 sudo qemu-utils udev
    - bin/build ${CLOUD_RELEASE} ${CLOUD_VENDOR} ${CLOUD_ARCH} ${CLOUD_IMAGE_NAME} ${CLOUD_OPTIONS}
    - 'xz -vk5T0 *.tar'
  artifacts:
    name: ${CLOUD_IMAGE_NAME}
    expire_in: 2 days
    paths:
      - '*.info'
      - '*.manifest.yml'
      - '*.tar.xz'

.only-pushes: &only-pushes
  only:
    - pushes
    - triggers

.only-web: &only-web
  only:
    - triggers
    - web

azure stretch build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: azure

azure stretch-backports build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch-backports
    CLOUD_IMAGE_RELEASE: 9-backports
    CLOUD_VENDOR: azure

azure buster build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: azure
  # no waagent in buster
  allow_failure: true

azure sid build:
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: azure

ec2 stretch build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: ec2

ec2 buster build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: ec2

ec2 sid build:
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: ec2

gce stretch build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: gce

gce buster build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: gce
  # uses external stuff
  allow_failure: true

gce sid build:
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: gce
  # uses external stuff
  allow_failure: true

nocloud stretch build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: nocloud

nocloud buster build:
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: nocloud

nocloud sid build:
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: nocloud
