---
variables:
  CLOUD_IMAGE_VERSION: dev
  CLOUD_IMAGE_NAME: debian-${CLOUD_IMAGE_RELEASE}-${CLOUD_IMAGE_VERSION}-${CLOUD_VENDOR}-${CLOUD_ARCH}

.build: &build
  stage: build
  image: debian:stretch-backports
  tags:
    - x86
  script:
    - apt-get update
    - >
      apt-get install --no-install-recommends -y -t stretch-backports
      ca-certificates debsums fai-server fai-setup-storage make python3 sudo qemu-utils udev
    - bin/build ${CLOUD_RELEASE} ${CLOUD_VENDOR} ${CLOUD_ARCH} ${CLOUD_IMAGE_NAME} ${CLOUD_OPTIONS}
    - 'xz -vk5T0 *.tar'
  artifacts:
    name: ${CLOUD_IMAGE_NAME}
    expire_in: 2 days
    paths:
      - '*.info'
      - '*.manifest.yml'
      - '*.tar.xz'

azure stretch build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: azure
  only:
    - triggers
    - web

azure stretch-backports build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch-backports
    CLOUD_IMAGE_RELEASE: 9-backports
    CLOUD_VENDOR: azure
  only:
    - triggers
    - web

azure buster build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: azure
  only:
    - triggers
    - web
  # no waagent in buster
  allow_failure: true

azure sid build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: azure
  only:
    - pushes
    - triggers

ec2 stretch build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: ec2
  only:
    - triggers
    - web

ec2 buster build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: ec2
  only:
    - triggers
    - web

ec2 sid build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: ec2
  only:
    - triggers
    - pushes

gce stretch build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: gce
  only:
    - triggers
    - web

gce buster build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: gce
  only:
    - triggers
    - web
  # uses external stuff
  allow_failure: true

gce sid build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: gce
  only:
    - pushes
    - triggers
  # uses external stuff
  allow_failure: true

nocloud stretch build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_IMAGE_RELEASE: 9
    CLOUD_VENDOR: nocloud
  only:
    - triggers
    - web

nocloud buster build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_IMAGE_RELEASE: 10
    CLOUD_VENDOR: nocloud
  only:
    - triggers
    - web

nocloud sid build:
  <<: *build
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_IMAGE_RELEASE: sid
    CLOUD_VENDOR: nocloud
  only:
    - pushes
    - triggers
