---
stages:
  - build
  - vendor upload

variables:
  CLOUD_IMAGE_VERSION: dev
  CLOUD_IMAGE_NAME: debian-${CLOUD_RELEASE}-${CLOUD_IMAGE_VERSION}-${CLOUD_VENDOR}-${CLOUD_ARCH}

.build: &build
  stage: build
  image: debian:buster
  script:
    - apt-get update
    - >
      apt-get install --no-install-recommends -y
      ca-certificates debsums dosfstools fai-server fai-setup-storage make python3 qemu-user-static qemu-utils udev
    - |
      if [ "$CI_DISPOSABLE_ENVIRONMENT" ]; then
        # Do manual binfmt-misc support, see #910952
        mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
        echo ':qemu-aarch64-test:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:OCF' > /proc/sys/fs/binfmt_misc/register
        echo ':qemu-ppc64le-test:M::\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15\x00:\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\x00:/usr/bin/qemu-ppc64le-static:OCF' > /proc/sys/fs/binfmt_misc/register
        # Some of our build environments run with SELinux enabled, make sure it is detected by all the tools
        if [ -d /sys/fs/selinux ]; then mount -t selinuxfs none /sys/fs/selinux; mkdir -p /etc/selinux; touch /etc/selinux/config; fi
      fi
    - >
      echo
      python3 -m debian_cloud_images.cli.build
      ${CLOUD_RELEASE} ${CLOUD_VENDOR} ${CLOUD_ARCH} ${CLOUD_IMAGE_NAME} ${CLOUD_IMAGE_VERSION} ${CLOUD_OPTIONS}
    - >
      python3 -m debian_cloud_images.cli.build
      ${CLOUD_RELEASE} ${CLOUD_VENDOR} ${CLOUD_ARCH} ${CLOUD_IMAGE_NAME} ${CLOUD_IMAGE_VERSION} ${CLOUD_OPTIONS}
    - 'xz -vk5T0 *.tar'
  artifacts:
    name: ${CLOUD_IMAGE_NAME}
    expire_in: 7 days
    paths:
      - '*.build.json'
      - '*.info'
      - '*.tar.xz'

####
# Different selections when builds will be done
####

.only-pushes: &only-pushes
  only:
    - pushes

.only-triggers-official: &only-triggers-official
  only:
    - triggers@cloud-team/debian-cloud-images

.only-web: &only-web
  only:
    - web

####
# Builds for developer uploads pushes
####

azure stretch build: &build-azure-stretch
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: azure

azure stretch-backports build: &build-azure-stretch-backports
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch-backports
    CLOUD_VENDOR: azure

azure buster build: &build-azure-buster
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: azure
  # no waagent in buster
  allow_failure: true

azure sid build: &build-azure-sid
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: azure

ec2 stretch build: &build-ec2-stretch
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: ec2

ec2 buster build: &build-ec2-buster
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: ec2

ec2 sid build: &build-ec2-sid
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: ec2

gce stretch build: &build-gce-stretch
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: gce

gce buster build: &build-gce-buster
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: gce
  # uses external stuff
  allow_failure: true

gce sid build: &build-gce-sid
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: gce
  # uses external stuff
  allow_failure: true

nocloud stretch amd64 build: &build-nocloud-stretch-amd64
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: nocloud

nocloud buster amd64 build: &build-nocloud-buster-amd64
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: nocloud

nocloud sid amd64 build: &build-nocloud-sid-amd64
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: nocloud

nocloud stretch amd64-efi build: &build-nocloud-stretch-amd64-efi
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64-efi
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: nocloud

nocloud buster amd64-efi build: &build-nocloud-buster-amd64-efi
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64-efi
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: nocloud

nocloud sid amd64-efi build: &build-nocloud-sid-amd64-efi
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64-efi
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: nocloud

nocloud sid arm64 build: &build-nocloud-sid-arm64
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: arm64
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: nocloud

nocloud sid ppc64el build: &build-nocloud-sid-ppc64el
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: ppc64el
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: nocloud
  # is just built for test purposes
  allow_failure: true

openstack buster amd64 build: &build-openstack-buster-amd64
  <<: *build
  <<: *only-web
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: openstack

openstack sid amd64 build: &build-openstack-sid-amd64
  <<: *build
  <<: *only-pushes
  tags:
    - x86
  variables:
    CLOUD_ARCH: amd64
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: openstack

####
# Official builds done on Debian hardware
####

azure stretch build official:
  <<: *build-azure-stretch
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

azure stretch-backports build official:
  <<: *build-azure-stretch-backports
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

azure buster build official:
  <<: *build-azure-buster
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

azure sid build official:
  <<: *build-azure-sid
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

ec2 stretch build official:
  <<: *build-ec2-stretch
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

ec2 buster build official:
  <<: *build-ec2-buster
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

ec2 sid build official:
  <<: *build-ec2-sid
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

gce stretch build official:
  <<: *build-gce-stretch
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

gce buster build official:
  <<: *build-gce-buster
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

gce sid build official:
  <<: *build-gce-sid
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

nocloud stretch amd64 build official:
  <<: *build-nocloud-stretch-amd64
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

nocloud buster amd64 build official:
  <<: *build-nocloud-buster-amd64
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

nocloud sid amd64 build official:
  <<: *build-nocloud-sid-amd64
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

nocloud stretch amd64-efi build official:
  <<: *build-nocloud-stretch-amd64-efi
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

nocloud buster amd64-efi build official:
  <<: *build-nocloud-buster-amd64-efi
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

nocloud sid amd64-efi build official:
  <<: *build-nocloud-sid-amd64-efi
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

openstack buster amd64 build official:
  <<: *build-openstack-buster-amd64
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

openstack sid amd64 build official:
  <<: *build-openstack-sid-amd64
  <<: *only-triggers-official
  tags:
    - debian-cloud-images-build
    - x86

####
# Provider uploads for developer pushs
####

ec2 upload:
  stage: vendor upload
  image: debian:buster
  script:
    - apt-get update
    - apt-get install --no-install-recommends -y python3-libcloud
    - >
      echo
      python3 -m debian_cloud_images.cli.upload_ec2
      --version-override "'${CI_PROJECT_NAMESPACE}-${CI_PIPELINE_ID}'"
      --regions "'${CLOUD_UPLOAD_EC2_DEV_REGIONS}'"
      "'${CLOUD_UPLOAD_EC2_DEV_BUCKET}'"
    - >
      python3 -m debian_cloud_images.cli.upload_ec2
      --version-override "${CI_PROJECT_NAMESPACE}-${CI_PIPELINE_ID}"
      --regions "${CLOUD_UPLOAD_EC2_DEV_REGIONS}"
      "${CLOUD_UPLOAD_EC2_DEV_BUCKET}"
  dependencies:
    - ec2 stretch build
    - ec2 buster build
    - ec2 sid build
  only:
    refs:
      - pushes
      - web
    variables:
      - $CLOUD_UPLOAD_EC2_DEV_ENABLED == "1"
  artifacts:
    name: ${CLOUD_IMAGE_NAME}-upload_vendor
    expire_in: 7 days
    paths:
      - '*.upload_vendor.json'

gce upload:
  stage: vendor upload
  image: debian:buster
  script:
    - apt-get update
    - apt-get install --no-install-recommends -y python3-libcloud
    - echo "${CLOUD_UPLOAD_GCE_AUTH}" > .auth
    - >
      python3 -m debian_cloud_images.cli.upload_gce
      --auth .auth
      --version-override "${CI_PROJECT_NAMESPACE}-${CI_PIPELINE_ID}"
      "${CLOUD_UPLOAD_GCE_DEV_PROJECT}" "${CLOUD_UPLOAD_GCE_DEV_BUCKET}"
  dependencies:
    - gce stretch build
    - gce buster build
    - gce sid build
  only:
    refs:
      - pushes
      - web
    variables:
      - $CLOUD_UPLOAD_GCE_DEV_ENABLED == "1"
  artifacts:
    name: ${CLOUD_IMAGE_NAME}-upload_vendor
    expire_in: 7 days
    paths:
      - '*.upload_vendor.json'
