---
variables:
  CLOUD_IMAGE_VERSION: dev

.build: &build
  stage: build
  image: debian:stretch-backports
  tags:
    - x86
  script:
    - BASE=${CLOUD_VENDOR}-${CLOUD_RELEASE}-${CLOUD_IMAGE_VERSION}-image
    - apt-get update
    - >
      apt-get install --no-install-recommends -y -t stretch-backports
      ca-certificates debsums fai-server fai-setup-storage make python3 sudo qemu-utils udev
    - bin/build ${CLOUD_RELEASE} ${CLOUD_VENDOR} amd64 ${BASE} ${CLOUD_OPTIONS}
    - 'xz -vk5T0 *.tar'
  artifacts:
    name: $CLOUD_VENDOR-$CLOUD_RELEASE-$CLOUD_IMAGE_VERSION-image
    expire_in: 2 days
    paths:
      - '*.info'
      - '*.manifest.yml'
      - '*.tar.xz'

azure stretch build:
  <<: *build
  variables:
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: azure
  only:
    - web

azure stretch-backports build:
  <<: *build
  variables:
    CLOUD_RELEASE: stretch-backports
    CLOUD_VENDOR: azure
  only:
    - web

azure buster build:
  <<: *build
  variables:
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: azure
  only:
    - web
  # no waagent in buster
  allow_failure: true

azure sid build:
  <<: *build
  variables:
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: azure
  only:
    - pushes

ec2 stretch build:
  <<: *build
  variables:
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: ec2
  only:
    - web

ec2 buster build:
  <<: *build
  variables:
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: ec2
  only:
    - web

ec2 sid build:
  <<: *build
  variables:
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: ec2
  only:
    - pushes

gce stretch build:
  <<: *build
  variables:
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: gce
  only:
    - web

gce buster build:
  <<: *build
  variables:
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: gce
  only:
    - web
  # uses external stuff
  allow_failure: true

gce sid build:
  <<: *build
  variables:
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: gce
  only:
    - pushes
  # uses external stuff
  allow_failure: true

nocloud stretch build:
  <<: *build
  variables:
    CLOUD_RELEASE: stretch
    CLOUD_VENDOR: nocloud
  only:
    - web

nocloud buster build:
  <<: *build
  variables:
    CLOUD_RELEASE: buster
    CLOUD_VENDOR: nocloud
  only:
    - web

nocloud sid build:
  <<: *build
  variables:
    CLOUD_RELEASE: sid
    CLOUD_VENDOR: nocloud
  only:
    - pushes
